# Generated by Django 4.2.5 on 2023-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_location_organization_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocated_budget', models.FloatField()),
                ('team_size', models.IntegerField(default=3)),
                ('is_deployed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('stage', models.IntegerField(choices=[(0, 'Draft'), (1, 'Requirements Gathering'), (2, 'Designing'), (3, 'Prototype Prepared'), (4, 'Pending Development'), (5, 'Under Development'), (6, 'Code review'), (7, 'Development work Completed'), (8, 'Testing'), (9, 'Deployed to Production'), (10, 'Project Completed')], default=0)),
            ],
        ),
    ]
