# Generated by Django 4.2.5 on 2023-10-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cafeteria_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='seating_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='polls.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='polls.organization'),
        ),
    ]
