# Generated by Django 4.2.5 on 2023-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_location_cafeteria_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_by', models.CharField(verbose_name=1000)),
                ('image_id', models.IntegerField()),
                ('twitter_handle', models.CharField()),
                ('delete_info', models.CharField(max_length=100)),
                ('mapped_inv_id', models.IntegerField()),
                ('site_link', models.CharField()),
            ],
        ),
    ]
