# Generated by Django 4.2.5 on 2023-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_investor_created_by_alter_investor_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='delete_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='image_id',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='mapped_inv_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Investor Name'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='site_link',
            field=models.CharField(null=True, verbose_name='Site Link'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='twitter_handle',
            field=models.CharField(null=True, verbose_name='Twitter Handle'),
        ),
    ]
