# Generated by Django 4.2.5 on 2023-10-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_investor_created_by_alter_investor_delete_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='image_id',
            new_name='image',
        ),
    ]
